// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitterCloneBack.Dal;

#nullable disable

namespace TwitterCloneBack.Dal.Migrations
{
    [DbContext(typeof(TwitterCloneContext))]
    [Migration("20260505175525_AddPostReplies")]
    partial class AddPostReplies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TwitterCloneBack.Dal.Like.Dao.LikeDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LikedById")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LikedById");

                    b.HasIndex("PostId", "LikedById")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("TwitterCloneBack.Dal.Post.Dao.PostDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ReplyToPostId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Posts__3214EC074E84AA35");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReplyToPostId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TwitterCloneBack.Dal.User.Dao.UserDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DisplayUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07EB2A0E6C");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4FB423C01")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105341996ED1A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TwitterCloneBack.Dal.Like.Dao.LikeDao", b =>
                {
                    b.HasOne("TwitterCloneBack.Dal.User.Dao.UserDao", "LikedBy")
                        .WithMany("Likes")
                        .HasForeignKey("LikedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitterCloneBack.Dal.Post.Dao.PostDao", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LikedBy");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TwitterCloneBack.Dal.Post.Dao.PostDao", b =>
                {
                    b.HasOne("TwitterCloneBack.Dal.User.Dao.UserDao", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_To_Users");

                    b.HasOne("TwitterCloneBack.Dal.Post.Dao.PostDao", "ReplyToPost")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToPostId");

                    b.Navigation("Author");

                    b.Navigation("ReplyToPost");
                });

            modelBuilder.Entity("TwitterCloneBack.Dal.Post.Dao.PostDao", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TwitterCloneBack.Dal.User.Dao.UserDao", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
