/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface CreateUser {
    username: string;
    email: string;
    displayUsername: string;
    password: string;
    bio?: string | null;
}

export interface GetPost {
    id?: number;
    authorId?: number;
    textContent?: string | null;
    createdAt?: Date;
}

export interface GetUser {
    id?: number;
    username?: string | null;
    displayUsername?: string | null;
    bio?: string | null;
    createdAt?: Date;
}

export interface PostDto {
    id?: number;
    authorId?: number;
    textContent?: string | null;
    isDeleted?: boolean;
    createdAt?: Date;
}

export interface UpdatePost {
    id?: number;
    textContent?: string | null;
}

export interface UpdateUser {
    id?: number;
    username?: string | null;
    displayUsername?: string | null;
    bio?: string | null;
    password?: string | null;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
