/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Like controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, LikeDto } from "../models";

@Injectable({ providedIn: "root" })
export class LikeService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiV1LikeLikeIdGet(likeId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<LikeDto>;
    apiV1LikeLikeIdGet(likeId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LikeDto>>;
    apiV1LikeLikeIdGet(likeId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LikeDto>>;
    apiV1LikeLikeIdGet(likeId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/${likeId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1LikePostPostIdGet(postId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<LikeDto>>;
    apiV1LikePostPostIdGet(postId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<LikeDto>>>;
    apiV1LikePostPostIdGet(postId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<LikeDto>>>;
    apiV1LikePostPostIdGet(postId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/post/${postId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1LikeUserUserIdGet(userId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<LikeDto>>;
    apiV1LikeUserUserIdGet(userId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<LikeDto>>>;
    apiV1LikeUserUserIdGet(userId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<LikeDto>>>;
    apiV1LikeUserUserIdGet(userId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/user/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1LikePostPostIdCountGet(postId: number, observe?: 'body', options?: RequestOptions<'text'>): Observable<number>;
    apiV1LikePostPostIdCountGet(postId: number, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<number>>;
    apiV1LikePostPostIdCountGet(postId: number, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<number>>;
    apiV1LikePostPostIdCountGet(postId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/post/${postId}/count`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            responseType: 'text' as 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1LikePostPostIdUserUserIdGet(postId: number, userId: number, observe?: 'body', options?: RequestOptions<'text'>): Observable<boolean>;
    apiV1LikePostPostIdUserUserIdGet(postId: number, userId: number, observe?: 'response', options?: RequestOptions<'text'>): Observable<HttpResponse<boolean>>;
    apiV1LikePostPostIdUserUserIdGet(postId: number, userId: number, observe?: 'events', options?: RequestOptions<'text'>): Observable<HttpEvent<boolean>>;
    apiV1LikePostPostIdUserUserIdGet(postId: number, userId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/post/${postId}/user/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            responseType: 'text' as 'text',
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1LikePostIdUserIdPost(postId: number, userId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<LikeDto>;
    apiV1LikePostIdUserIdPost(postId: number, userId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LikeDto>>;
    apiV1LikePostIdUserIdPost(postId: number, userId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LikeDto>>;
    apiV1LikePostIdUserIdPost(postId: number, userId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/${postId}/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    apiV1LikePostIdUserIdDelete(postId: number, userId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<LikeDto>;
    apiV1LikePostIdUserIdDelete(postId: number, userId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LikeDto>>;
    apiV1LikePostIdUserIdDelete(postId: number, userId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LikeDto>>;
    apiV1LikePostIdUserIdDelete(postId: number, userId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/like/${postId}/${userId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
