/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Post controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GetPost, PostDto, UpdatePost } from "../models";

@Injectable({ providedIn: "root" })
export class PostService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiV1PostsIdGet(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetPost>;
    apiV1PostsIdGet(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetPost>>;
    apiV1PostsIdGet(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetPost>>;
    apiV1PostsIdGet(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1PostsIdDelete(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDto>;
    apiV1PostsIdDelete(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDto>>;
    apiV1PostsIdDelete(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDto>>;
    apiV1PostsIdDelete(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    apiV1PostsGet(page?: number, pageSize?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<GetPost>>;
    apiV1PostsGet(page?: number, pageSize?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<GetPost>>>;
    apiV1PostsGet(page?: number, pageSize?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<GetPost>>>;
    apiV1PostsGet(page?: number, pageSize?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts`;

        let params = new HttpParams();
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1PostsPost(postDto?: PostDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDto>;
    apiV1PostsPost(postDto?: PostDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDto>>;
    apiV1PostsPost(postDto?: PostDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDto>>;
    apiV1PostsPost(postDto?: PostDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, postDto, requestOptions);
    }

    apiV1PostsPatch(updatePost?: UpdatePost, observe?: 'body', options?: RequestOptions<'json'>): Observable<PostDto>;
    apiV1PostsPatch(updatePost?: UpdatePost, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PostDto>>;
    apiV1PostsPatch(updatePost?: UpdatePost, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PostDto>>;
    apiV1PostsPatch(updatePost?: UpdatePost, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/posts`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, updatePost, requestOptions);
    }
}
