/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for User controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GetUser, CreateUser, UpdateUser } from "../models";

@Injectable({ providedIn: "root" })
export class UserService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiV1UsersIdGet(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetUser>;
    apiV1UsersIdGet(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetUser>>;
    apiV1UsersIdGet(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetUser>>;
    apiV1UsersIdGet(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1UsersIdDelete(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetUser>;
    apiV1UsersIdDelete(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetUser>>;
    apiV1UsersIdDelete(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetUser>>;
    apiV1UsersIdDelete(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    apiV1UsersGet(page?: number, pageSize?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<GetUser>>;
    apiV1UsersGet(page?: number, pageSize?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<GetUser>>>;
    apiV1UsersGet(page?: number, pageSize?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<GetUser>>>;
    apiV1UsersGet(page?: number, pageSize?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users`;

        let params = new HttpParams();
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiV1UsersPost(createUser?: CreateUser, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetUser>;
    apiV1UsersPost(createUser?: CreateUser, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetUser>>;
    apiV1UsersPost(createUser?: CreateUser, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetUser>>;
    apiV1UsersPost(createUser?: CreateUser, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createUser, requestOptions);
    }

    apiV1UsersPatch(updateUser?: UpdateUser, observe?: 'body', options?: RequestOptions<'json'>): Observable<GetUser>;
    apiV1UsersPatch(updateUser?: UpdateUser, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GetUser>>;
    apiV1UsersPatch(updateUser?: UpdateUser, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GetUser>>;
    apiV1UsersPatch(updateUser?: UpdateUser, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v1/users`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, updateUser, requestOptions);
    }
}
